### ISSUE TITLE
which bios to enter?

### ISSUE THREAD

**Issue by smartDev22** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#1]
which bios to enter? Please help

**Comment by ankanpratik** [comment]
Sorry couldn't understand? If you mean what BIOS settings to use then look at the official guide here: https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#intel-bios-settings

You can enter BIOS by pressing DEL key.

**Comment by smartDev22** [comment]
thanks
