### ISSUE TITLE
Continuous restarts with ethernet cable connected to the Mainboard

### ISSUE THREAD

**Issue by xretem** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#10]
Hi, I replaced my Graphics card (NVIDIA GTX 760 2GB) with AMD RX570 Pulse 8GB. Unfortunately I can not complete the installation, it restarts when I get to the latest configurations. I've tried to complete installation using another EFI for the Z490 Vision D (FENVI don't work) but I'd rather use yours since it's just for my card. can you help me?
I have your same motherboard and processor in the I7 10700.

UPDATE 01: after completing the installation I mounted your efi and after a few minutes from power on it restarted. I know or noticed that by unplugging the lan cable the problem disappears and it doesn't restart anymore. despite having Fenvi I need to use the lan, how can I solve the problem?

UPDATE 02: I updated your EFI following OPTION 1 at link https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225-V_FIX.md IMPROTANT your efi already contained SSDT-I225V.aml but I preferred to replace it with the one in the link.
Now everything seems to work. I'm not an expert and I would like your opinion if the steps I've done are correct or if I've done something wrong. I test it a few more hours and then try to do a clean install with the new EFI.

UPDATE 03: I installed with the new EFI without any problems, everything worked, I have no problems. I also upgraded to version 13.3.1. The only thing that doesn't work is the first one USB that is next to the ethernet port, can you give me an explanation?

**Comment by ankanpratik** [comment]
USB isn't working because of the 15 port limit, you can use USB Toolbox to generate the Kext, keep in mind you have to limit the number of USB ports to 15. https://github.com/USBToolBox/tool

**Comment by allluke** [comment]
Hi following the above instructions I can get the the ethernet to work fine and the bluetooth, but not my wifi.

I've got almost the same setup. Same Motherboards, Same CPU, Fenvi too just a different case and GPU I'm using a Radeon 6600 which is working fine. I've done the USB Mapping and that's all good I just can't get wifi to work.

I'm also on 0.9.2 I updated.

Do you have any suggestions.?

**Comment by ankanpratik** [comment]
If you have Ethernet/Wifi Issues, try different variations of DisableIOMapper and DisableIOMapperMapping. Also try the BIOS setting for VTd in Advanced CPU Settings > VT-d: Enabled.

**Comment by allluke** [comment]
No luck sadly, I have VT-d on if I turn it off I get boot loops, and if I enable DiasableIOMapper I get bootloops haha. I can use both enabled or disabled DisableIOMapperMapping but no wifi sadly.

**Comment by ankanpratik** [comment]
In that case make sure you've properly setup USB Port Mapping correctly. In my case the configuration is like this below. If this doesn't work, try XhciPortLimit to be Enabled as the last resort.
<img width="992" alt="Screenshot 2023-06-09 at 10 50 07 AM" src="https://github.com/ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore/assets/9656361/de645aec-1379-464e-8f9f-28901f3b1aec">

**Comment by allluke** [comment]
Thanks. Out of curiosity you don’t have the  fenvi showing there’s no internal ? I’ve created my mapping with it internal is this incorrect?

**Comment by ankanpratik** [comment]
Shouldn't matter regardless. Try disabling Port Mapping Kext and Enabling XhciPortLimit, it should work.

**Comment by allluke** [comment]
Just tried that and still no luck.

**Comment by allluke** [comment]
![Image 9-06-23 at 8 00 PM](https://github.com/ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore/assets/104663380/9b9ae99a-a8bd-4f59-9560-c798e9f4937e)
This is my USB Port Mapping which I did in Windows via the suggested OpenCore method using USBToolBox.kext and the produced UTBMap.kext.

**Comment by allluke** [comment]
and in case you are wondering, the wifi works in Windows so it's not broken :-)

**Comment by ankanpratik** [comment]
HS14 is removed from the list, that is the internal header for Wifi, add it back to the USBMap and check if it works?

**Comment by allluke** [comment]
Hey thank you for you assistance, I did get it working just now. My fault I removed under ACPI --> Delete --> Drop OEM DMAR table as I'd read it wasn't required. Turns out it is required so adding it back has fixed the wifi issue. I've also tidied up my USB Mapping as you suggested.
