### ISSUE TITLE
Modified EFI sharing : Got lan back to function

### ISSUE THREAD

**Issue by Archmage-Cirno** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#12]
Hi! Thank you so much for sharing and keep updating your EFI build, it's really robust and I've been using it since last year. It really helped me a lot!
Starting from Ventura, the lan problem kept bothering me as my BCM wifi card bad at receiving signal, which got much poorer signal level than the intel wifi. I gave up after tried a few solutions. 
Recently I got my GPU updated, and I modified my EFI based on yours, and have just got lan working normally again today, which was a real struggle. I'm sharing my EFI here and hope it could be of help to you.
The CPU is 10600K and GPU is spoofed 6900XTXH (updated from RX460). The intel wifi is still mounted on board, normally unused in hackintosh, but still could be mounted using Heliport when necessary. The BCM card is BCM94360CD.

https://drive.google.com/file/d/14yZ7XYRE2bK5_8hPeC0EMfxIzRtoUgcC/view?usp=sharing
![Screenshot 2023-08-24 at 01 42 12](https://github.com/ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore/assets/75807487/c3c4a040-895a-4d45-8d1a-e88fbcb50780)
![Screenshot 2023-08-24 at 01 42 45](https://github.com/ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore/assets/75807487/be784256-cbb7-4ddb-8fea-30db285273b8)
![Screenshot 2023-08-24 at 01 44 02](https://github.com/ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore/assets/75807487/cb018434-0dca-488a-b091-c3517a8c020e)
![Screenshot 2023-08-24 at 01 43 07](https://github.com/ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore/assets/75807487/f4987f34-0841-4822-915a-0c222fdd3eb6)

**Comment by ankanpratik** [comment]
Oh awesome news @Archmage-Cirno. I'll check and get back on this update.
