### ISSUE TITLE
About XMP slowing down the os 

### ISSUE THREAD

**Issue by 3rdeyeoptics** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#13]
Hey Ankan : How are you ?

I have the same build as yours , I successfully installed following your guide . Thank you very much . 
But whenever I enable XMP , the os just became unusable . sluggish , and really slow . 
Could you tell me some tips to solve it ? are you running your ram on full speed ?

My Setup:
CPU: Intel i7-10700k
RAM: Corsair Vengeance 64GB 3600MHz
GPU: ASUS TUF RX 6900 XT
PSU: Thermaltake Toughpower PF1 1050W | 80Plus Platinum
Motherboard: AORUS Z490 Pro AX
Storage: 3x Samsung 970 EVO 1TB NVMe SSDs

Thank you in advance for your help .

**Comment by ankanpratik** [comment]
Hi, are you using the iMac 20,1 SMBIOS? iMacPro 1,1 also works but there could be issues sometimes, and 10700k is natively supported through 20,1 so theoratically it should work. Try replacing your EFI with the build shared here and change the PlatformInfo > SystemSerialNumber, SystemUUID, and MLB to your systems 20,1 info and check if it works fine.
