### ISSUE TITLE
use fcpx and preview certain specific effects, the system will crash and restart

### ISSUE THREAD

**Issue by L1Nj** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#14]
My configuration is as follows: Gigabyte z490 aorus pro ax, 10900K, RX 6950 XT graphics card, the current installed system version: 15.0 (24A335), when I use fcpx and preview certain specific effects, the system will crash and restart, and after the restart, there is no prompt, and there is no mention of the crash information in the log, which makes me very helpless. When I use Sonoma 14.7 (23H124), the same is true. I don’t know if there is a problem with my hardware or an error in the efi configuration. I am a beginner, so I don’t know what to do. Can anyone help me? Thank you very much

**Comment by ankanpratik** [comment]
Hi, hope you're using agdpmod=pikera in the boot-args for this card. 
Also try using https://github.com/ChefKissInc/NootRX kext for your driver. 

(Alternate for Noot) As far I've heard, people downgrade this card to Spoof 6900XT card as mentioned in the Dortiana Guide as well (https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#navi-23-series)

If you want crash reports to analyze the crash, change the OpenCore files to Debug Version. https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html
Once you've changed the files (you can also use OCAuxilaryTools for this as well), you'll find all the logs in your EFI Folder.

Another beginner friendly alternative is https://github.com/lzhoang2801/OpCore-Simplify. Your card is supported as I see in the GPU list, I think this is the best alternative for you if NootRX doesn't work. 

Try adding NootRX kext with the agdpmod=pikera in the boot-args first on your current EFI, and let me know!

**Comment by L1Nj** [comment]
Thank you for your reply. Yes, as you said, I tried NootRX, but it didn't work. On the contrary, it couldn't boot normally after using it. I have been using the method of impersonating 6900xt, and the startup parameter agdpmod=pikera has been added. I think I have successfully driven the graphics card. In the rendering stage, the graphics card is working, but it crashes when using certain special effects, which makes me very confused.

**Comment by ankanpratik** [comment]
Hi, try to create an EFI with this repo: https://github.com/lzhoang2801/OpCore-Simplify

**Comment by L1Nj** [comment]
The efi I'm using now was created using this project. It just helped me install the drivers for wifi and bluetooth. This is not very important to me. The original problem still exists. I think I can only use it this way. Thank you very much for recommending this project. At least it helped me.

**Comment by L1Nj** [comment]
Ah, I finally found the reason. It turned out to be the graphics card power supply line. I used to use an 8-pin to dual 8-pin power supply line that was split into two. Now I use two separate 8-pins. This problem that has troubled me for a long time has been solved.
