### ISSUE TITLE
Grey screen and black mouse

### ISSUE THREAD

**Issue by pwnz0r69** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#4]
Hello.
I have exactly the same configuration but with an intel 10600kf without igpu and rx6800.
I have tried with macpro7,1 and iMacPro1,1
Bu I have always a grey screen and black mouse at the first installation screen of Monterey.
What do you think?

thx by advance

**Comment by ankanpratik** [comment]
Hey, ideally the RX6800 should work well with imacpro1,1, but you could try adding the boot variable on `NVRAM > 7C436110-AB2A-4BBB-A880-FE41995C9F82 > boot-args > shikigva=40 shiki-id=Mac-7BA5B2D9E42DDD94`

In theory this should fix it. https://dortania.github.io/GPU-Buyers-Guide/misc/bootflag.html

**Comment by wutaijieing** [comment]
Clean up NVRAM > 7C436110-AB2A-4BBB-A880-FE41995C9F82 > prev-lang:kbd
