### ISSUE TITLE
Fix onboard wifi ax201 and Intel i225V, Monterey Ventura

### ISSUE THREAD

**Issue by wutaijieing** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#5]
Fix onboard wifi ax201 and Intel i225V, Monterey Ventura

AX201:
ACPI>Add> z490_ aorus_ pro_ ax_ DMAR. aml [enabled] true

ACPI>Delete> [Comment Drop] OEM DMAR Table [Enabled] true [OemTableId] 45444B3220202020 [TableLength] 0 [TableSignature] 444D4152

Kernel>Quirks>DisableIoMapper false

[z490_ aorus_ pro_ ax_ DMAR. aml](https://drive.google.com/file/d/1lBLjmR7bS4E8aEACgdSab_g_SOon2GF3/view?usp=sharing)

i225V:
DeviceProperties>Add 
Deletes the configuration of Intel i225V

NVRAM>Add>7C436110-AB2A-4BBB-A880-FE41995C9F82>boot-args>dk.e1000=0

**Comment by chaun85** [comment]
[z490_ aorus_ pro_ ax_ DMAR. aml](https://drive.google.com/file/d/1lBLjmR7bS4E8aEACgdSab_g_SOon2GF3/view?usp=sharing) do not download?

**Comment by ankanpratik** [comment]
Tried all the steps but still not working, will need help if anyone else has figured this out for Ventura.

**Comment by wutaijieing** [comment]
> Tried all the steps but still not working, will need help if anyone else has figured this out for Ventura.

try del NVRAM>Add>7C436110-AB2A-4BBB-A880-FE41995C9F82>boot-args>dk.e1000=0

**Comment by ankanpratik** [comment]
On Ventura, unless I add e1000=0, the AppleIntelI210Ethernet driver doesn't load. Can you share your EFI so that I could check and compare? Thanks
