### ISSUE TITLE
I fixed onboard Intel i225V in Ventura 13.2.1

### ISSUE THREAD

**Issue by Helms1997** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#6]
See this if you want to get the I225-v to work, yes I did and it works fine now.

https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225-V_FIX.md#flashing-the-firmware-with-openshell

**Comment by ankanpratik** [comment]
Thank you for your input @Helms1997 but I was trying to use the Option 1 before flashing the firmware as the last resort. I guess this is the only option for Ventura from now on.

**Comment by zyallday** [comment]
I have fixed onboard intel i225 with option 2. option 1 failed.
