### ISSUE TITLE
 just using kext can fix i225v issue

### ISSUE THREAD

**Issue by weiwei007** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#7]
using https://github.com/SongXiaoXi/AppleIGC will be work,no injection anythings of 225,remove 225-ssdt,the only thing if you freeze ethernet,the sata will be dismissing

**Comment by ankanpratik** [comment]
Thank you @weiwei007, I tried the Kext but it gets error Stop sign on boot and freezes as you said. How did you fix this?

**Comment by weiwei007** [comment]
i used t919 instead of , haha, if i need ethernet then open it
flashing a custom Firmware can fix i225 issues,i just don't want to change MAC Adrees
