### ISSUE TITLE
USB Boot

### ISSUE THREAD

**Issue by xretem** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#8]
Hi, I have your same setup, working perfectly on Big Sur through SchmockLord's guide. I have a trivial problem, my usb won't boot. I created it as always, 
sudo /Applications/Install\ macOS\ Ventura.app/Contents/Resources/createinstallmedia --volume /Volumes/USB /Applications/Install\ macOS\ Ventura.app --nointeraction
and then I replaced your EFI and created the symbios on config.plist Can you help me?

**Comment by xretem** [comment]
maybe i'm wrong to Open Config.plist and add SMBIOS details

**Comment by ankanpratik** [comment]
Use OCAT to open and generate SMBIOS details, that should work.
https://github.com/ic005k/OCAuxiliaryTools

**Comment by xretem** [comment]
Dont' boot! i try to copy only EFI on USB FAT32 and it boot. If i copy in EFI partition on Ventura USB it don't boot.

**Comment by ankanpratik** [comment]
FAT32 won't work for MacOS, it has to be HFS+ with GUID Partition table. Follow this guide to create a bootable USB first: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/ and then replace the EFI folder with this one with correct SMBIOS.

**Comment by xretem** [comment]
sorry but my head is in the clouds, I kept copying only the BOOT and OC folders instead of the entire EFI folder. now all work
