### ISSUE TITLE
GTX 760 2GB

### ISSUE THREAD

**Issue by xretem** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#9]
I have your same (Mainboard, FENVI etc etc) configuration, only the video card varies I have a Nvidia GTX 760 2GB I can't finish the installation.

**Comment by ankanpratik** [comment]
GTX 760 is only supported till Big Sur.
https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/nvidia-gpu.html
You'll either have to buy AMD GPU or go with internal GPU of 10700k.
